/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author 57317
 */
public class VistaInicio extends javax.swing.JFrame {

  /**
   * Creates new form VistaInicio
   */
  public VistaInicio() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    pnlFondoinicio = new javax.swing.JPanel();
    lblTituloInicio = new javax.swing.JLabel();
    jLabel1 = new javax.swing.JLabel();
    txtfieldCorreo = new javax.swing.JTextField();
    jLabel2 = new javax.swing.JLabel();
    txtfieldNombre1 = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    txtfieldApellido1 = new javax.swing.JTextField();
    btnIngresar = new javax.swing.JButton();
    btnIngresar1 = new javax.swing.JButton();
    lblFondoInicio = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    pnlFondoinicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    lblTituloInicio.setBackground(new java.awt.Color(51, 51, 51));
    lblTituloInicio.setFont(new java.awt.Font("Ebrima", 2, 18)); // NOI18N
    lblTituloInicio.setForeground(new java.awt.Color(255, 255, 255));
    lblTituloInicio.setText("JUEGO DE PREGUNTAS Y RESPUESTAS");
    pnlFondoinicio.add(lblTituloInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 360, -1));

    jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(255, 255, 255));
    jLabel1.setText("Nombre: ");
    pnlFondoinicio.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 109, -1, 30));
    pnlFondoinicio.add(txtfieldCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 240, 30));

    jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    jLabel2.setForeground(new java.awt.Color(255, 255, 255));
    jLabel2.setText("Apellido:");
    pnlFondoinicio.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, -1, 30));
    pnlFondoinicio.add(txtfieldNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 240, 30));

    jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    jLabel3.setForeground(new java.awt.Color(255, 255, 255));
    jLabel3.setText("Correo:");
    pnlFondoinicio.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, -1, 30));
    pnlFondoinicio.add(txtfieldApellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 240, 30));

    btnIngresar.setBackground(new java.awt.Color(51, 51, 51));
    btnIngresar.setForeground(new java.awt.Color(255, 255, 255));
    btnIngresar.setText("REGISTRARME");
    btnIngresar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnIngresarActionPerformed(evt);
      }
    });
    pnlFondoinicio.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 150, -1));

    btnIngresar1.setBackground(new java.awt.Color(51, 51, 51));
    btnIngresar1.setForeground(new java.awt.Color(255, 255, 255));
    btnIngresar1.setText("INGRESAR");
    btnIngresar1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnIngresar1ActionPerformed(evt);
      }
    });
    pnlFondoinicio.add(btnIngresar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 300, 150, -1));

    lblFondoInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/preguntasfondo_1.jpg"))); // NOI18N
    pnlFondoinicio.add(lblFondoInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 410));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(pnlFondoinicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(pnlFondoinicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_btnIngresarActionPerformed

  private void btnIngresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresar1ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_btnIngresar1ActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(VistaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(VistaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(VistaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(VistaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new VistaInicio().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnIngresar;
  private javax.swing.JButton btnIngresar1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel lblFondoInicio;
  private javax.swing.JLabel lblTituloInicio;
  private javax.swing.JPanel pnlFondoinicio;
  private javax.swing.JTextField txtfieldApellido1;
  private javax.swing.JTextField txtfieldCorreo;
  private javax.swing.JTextField txtfieldNombre1;
  // End of variables declaration//GEN-END:variables
}
